trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: SECRETS

jobs:
- job: Build
  displayName: 'Build and Push Docker Image'
  steps:
  - script: |
      docker build -t containerregistry1z.azurecr.io/myapp:$(Build.BuildId) .
      docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
      docker push containerregistry1z.azurecr.io/myapp:$(Build.BuildId)
    displayName: 'Build and Push Docker Image'