trigger:
- main

variables:
  # Azure Container Registry (ACR) information
  acrName: 'containerregistry1z'
  azureSubscriptionEndpoint: '3f350cd7-7ec5-40cf-afbf-7a61b96e8396'
  dockerfilePath: '$(Build.SourcesDirectory)'
  imageRepository: 'myapp'
  containerRegistry: 'containerregistry1z.azurecr.io'
  dockerImageTag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        # Build and push Docker image
        docker build -f $(dockerfilePath) -t $(imageRepository):$(dockerImageTag) .
        docker tag $(imageRepository):$(dockerImageTag) $(containerRegistry)/$(imageRepository):$(dockerImageTag)
        docker push $(containerRegistry)/$(imageRepository):$(dockerImageTag)
      displayName: 'Build and push Docker image'
